// src/context/LanguageContext.jsx
import React, { createContext, useContext, useState, useEffect } from 'react'

const translations = {
    id: {
        // ── Home & Prepare ──
        homeDescription: 'Simulasi virtual Reaktor Kartini – Reaktor Riset TRIGA Mark II milik BRIN Yogyakarta. Kendalikan batang kontrol, pantau daya reaktor, dan pelajari fisika reaktor nuklir secara aman.',
        homeSubtitle: 'SISTEM SIMULATOR INTERAKTIF',
        homeProfesi: 'GLOWLAB KARTINI',
        profesiTitle: 'Pilih Peran Anda',
        profesiDesc: 'Masuk sebagai?',
        profesiAhli: 'Ahli',
        profesiPemula: 'Pemula',
        homePilih: 'PILIH MODE SIMULASI',
        homeKet: 'Mode standar untuk demonstrasi & pembelajaran, atau mode lanjutan dengan data reaktor nyata.',
        homeBack: '←',
        homePilihGame: 'GAME SIMULASI',
        homePilihKet: 'Dengan skor & gamifikasi',
        homePilihGame1: 'MODE IRL',
        homePilihKet1: 'Data reaktor real-time, tanpa skor',
        feature1Title: 'ZONA PEMBELAJARAN',
        feature1Desc: 'Pahami tentang Reaktor Kartini, Sejarah Reaktor Kartini, dan prinsip kerja Reaktor Kartini',
        feature2Title: 'TANTANGAN AWAL',
        feature2Desc: 'Mulai perjalananmu  dengan tantangan awal untuk menguji pemahaman dasar tentang Reaktor Kartini',
        feature3Title: 'ARENA SIMULASI',
        feature3Desc: 'Uji kemampuanmu dalam mengelola daya reaktor agar beroperasi pada daya yang stabil',
        feature4Title: 'TANTANGAN AKHIR',
        feature4Desc: 'Hadapi tantangan akhir untuk menguji pemahamanmu tentang Reaktor Kartini',
        // ── Navigasi & Button ──
        btnSelengkapnya: 'SELENGKAPNYA →',
        btnMulai: 'MULAI SIMULASI →',
        btnKembali: '← KEMBALI',
        hintKlik: 'Klik untuk memulai simulasi interaktif',
        // ── Footer ──
        footerText: '© 2026 Simulator Reaktor Kartini | BRIN Indonesia',
        footerSub: 'Dirancang untuk keperluan edukasi dan simulasi',
        // ── Section Labels ──
        sectionFeature: 'PANDUAN PENGGUNAAN',
        labelSpesifikasi: 'SPESIFIKASI',
        specsTitle: '⚛ SPESIFIKASI REAKTOR',
        requirementHint: 'Selesaikan Tahap 1 & 2 untuk membuka simulasi',
        //--feature card
        progressLabel: 'PROGRESS PEMBELAJARAN',
        progressLocked: 'Selesaikan terlebih dahulu:',
        progressDone: 'Tahap selesai!',
        progressIncomplete: 'Selesaikan semua tahap terlebih dahulu!',
        progressReset: ' Progress direset',
        resetProgress: '↺ Reset Progress',
        stepDone: ' Selesai',
        stepOpen: ' Buka',
        stepLocked: ' Terkunci',
        // ── Materi Page ──
        materiPageTitle: 'MATERI REAKTOR KARTINI',
        materiPageSubtitle: 'PENGETAHUAN DASAR REAKTOR NUKLIR',
        materiBack: '← KEMBALI',
        materiProgress: 'SELESAI MEMBACA',
        materiReadAll: 'Tandai Selesai',
        materiDone: '✓ Materi Selesai Dibaca',
        materiProgressLabel: 'PROGRESS MEMBACA',
        materiDoneBanner: 'Selamat! Kamu telah menyelesaikan semua materi. Zona Pembelajaran telah selesai!',
        materiTagDone: 'SELESAI',
        materiBackGuide: '← KEMBALI KE PANDUAN',
        // Sections
        materi1Title: 'Apa Itu Reaktor Kartini?',
        materi1Content: 'Reaktor Kartini adalah instalasi reaktor nuklir riset tipe TRIGA Mark II yang dimiliki dan dioperasikan oleh Badan Riset dan Inovasi Nasional (BRIN) di Yogyakarta, Indonesia. Sebagai reaktor nuklir, Reaktor Kartini merupakan tempat terjadinya reaksi pembelahan inti (fisi) secara terus-menerus dan terkendali. Reaktor ini memiliki daya nominal 100 kW dan telah beroperasi sejak tahun 1979. Nama "Kartini" diambil dari pahlawan nasional R.A. Kartini sebagai simbol kemajuan ilmu pengetahuan dan emansipasi. Reaktor Kartini dimanfaatkan untuk keperluan penelitian fisika reaktor, produksi radioisotop, pendidikan, serta pelatihan tenaga ahli nuklir nasional.',
        materi2Title: 'Sejarah Singkat',
        materi2Content: 'Reaktor Kartini dibangun pada tahun 1974 dan mulai beroperasi secara resmi pada tahun 1979. Reaktor ini dirancang dan diproduksi oleh General Atomics, Amerika Serikat. Fasilitas ini berada di bawah pengelolaan Pusat Sains dan Teknologi Akselerator (PSTA) BATAN Yogyakarta yang kini menjadi bagian dari BRIN. Selama lebih dari empat dekade, Reaktor Kartini telah menjadi tulang punggung penelitian fisika reaktor, pendidikan operator reaktor bersertifikat BAPETEN, serta pengembangan kompetensi nuklir di Indonesia. Reaktor Kartini merupakan salah satu fasilitas nuklir tertua yang masih aktif beroperasi di Indonesia.',
        materi3Title: 'Tipe TRIGA Mark II',
        materi3Content: 'TRIGA (Training, Research, Isotopes, General Atomics) Mark II adalah jenis reaktor riset yang dirancang khusus untuk pelatihan, penelitian, dan produksi isotop. Keunggulan utama reaktor tipe ini adalah faktor keselamatannya yang sangat tinggi karena menggunakan bahan bakar U-ZrH (Uranium-Zirkonium Hidrida) yang memiliki koefisien temperatur negatif. Ini berarti ketika suhu bahan bakar naik akibat kenaikan daya, reaktivitas reaktor akan otomatis turun sehingga daya reaktor turun dengan sendirinya (self-limiting). Mekanisme umpan balik suhu negatif ini membuat reaktor TRIGA sangat aman dan tahan terhadap kondisi runaway. Reaktor Kartini sebagai TRIGA Mark II menggunakan air ringan (H₂O) sebagai moderator sekaligus pendingin.',
        materi4Title: 'Komponen Utama Reaktor',
        materi4Content: 'Reaktor Kartini terdiri dari beberapa komponen utama yang bekerja secara terintegrasi: (1) Teras Reaktor tempat berlangsungnya reaksi fisi nuklir berisi elemen bahan bakar U-ZrH; (2) Batang Kendali terdiri dari Safety Rod, Shim Rod, dan Regulating Rod untuk mengontrol reaktivitas; (3) Moderator & Pendingin menggunakan air ringan (H₂O) untuk memperlambat neutron sekaligus mendinginkan reaktor; (4) Sistem Instrumentasi & Kendali (SIK) memantau fluks neutron menggunakan detektor jenis CIC (Compensated Ionization Chamber) dan menampilkan parameter operasi secara real-time; (5) Sistem Proteksi Reaktor sistem keselamatan berlapis yang menjamin operasi aman dan memicu SCRAM otomatis; (6) Perisai Biologi melindungi operator dan lingkungan dari paparan radiasi.',
        materi5Title: 'Batang Kendali (Control Rods)',
        materi5Content: 'Batang kendali merupakan komponen kritis dalam operasi reaktor yang berfungsi mengatur laju reaksi fisi dengan cara menyerap neutron. Reaktor Kartini memiliki tiga jenis batang kendali: (1) Safety Rod (Batang Pengaman) dibuat dari bahan penyerap neutron sangat kuat seperti Cadmium, digunakan sebagai pengaman saat start-up dan shutdown darurat (SCRAM), harus berada di posisi 100% agar reaktor dapat beroperasi; (2) Shim Rod (Batang Kompensasi) digunakan untuk kontrol reaktivitas kasar, menaikkan dan menurunkan daya reaktor secara besar; (3) Regulating Rod (Batang Pengatur) digunakan untuk fine-tuning daya reaktor secara presisi. Sistem kendali reaktor bekerja dalam tiga kalang: kalang start-up (menaikkan daya), kalang operasi (mempertahankan daya stabil), dan kalang shutdown (mematikan reaktor).',
        materi6Title: 'Prinsip Kerja Reaktor Nuklir',
        materi6Content: 'Reaktor nuklir bekerja berdasarkan prinsip reaksi fisi berantai yang terkendali. Neutron termal (energi ~0,025 eV, kecepatan 2200 m/detik) menumbuk inti Uranium-235, membentuk inti majemuk U-236 yang tidak stabil lalu membelah menjadi dua inti hasil belah, melepaskan 2–3 neutron baru dan energi sekitar 200 MeV per pembelahan. Neutron-neutron baru diperlambat moderator (air ringan) dari energi cepat menjadi termal, lalu menumbuk inti U-235 lain sehingga terbentuk reaksi berantai. Perubahan daya diatur melalui reaktivitas (ρ): reaktivitas positif (k>1) menaikkan daya, reaktivitas nol (k=1) menjaga daya stabil atau kritis, dan reaktivitas negatif (k<1) menurunkan daya ke kondisi subkritis.',
        materi7Title: 'Sistem Keselamatan SCRAM',
        materi7Content: 'SCRAM adalah sistem penghentian darurat reaktor yang bekerja secara otomatis ketika kondisi abnormal terdeteksi. Sistem proteksi Reaktor Kartini dirancang dengan filosofi pertahanan berlapis: (1) Lapisan Pertahanan Dasar memastikan reaktor beroperasi dalam batas normal; (2) Lapisan Pencegahan Gangguan mendeteksi kondisi abnormal sebelum menjadi berbahaya; (3) Sistem Trip Otomatis menjatuhkan semua batang kendali ke posisi 0% dalam hitungan detik ketika parameter melampaui batas aman. Parameter aktuasi SCRAM mencakup daya berlebih, laju kenaikan daya terlalu cepat (periode reaktor pendek), dan kegagalan sistem pendingin. Setelah SCRAM, reaktor hanya dapat dioperasikan kembali setelah reset manual oleh operator bersertifikat untuk memastikan penyebab SCRAM telah diatasi.',
        materi8Title: 'Efek Cherenkov',
        materi8Content: 'Efek Cherenkov adalah cahaya biru yang terlihat di kolam reaktor nuklir. Fenomena ini terjadi ketika partikel bermuatan (seperti elektron hasil radiasi) bergerak melalui air dengan kecepatan lebih tinggi dari kecepatan cahaya dalam medium tersebut. Sama seperti boom sonik pesawat supersonik, partikel yang bergerak sangat cepat ini menghasilkan "ledakan cahaya" yang tampak berwarna biru keunguan. Efek ini merupakan tanda bahwa reaktor sedang beroperasi aktif.',
        materi9Title: 'Kegunaan Reaktor Kartini',
        materi9Content: 'Reaktor Kartini memiliki berbagai fungsi penting bagi ilmu pengetahuan dan teknologi: (1) Penelitian Fisika Reaktor mempelajari kinetika reaktor, pengukuran reaktivitas batang kendali, koefisien suhu bahan bakar, kekritisan reaktor, dan fluks neutron; (2) Kalibrasi Daya melakukan pengukuran dan kalibrasi kanal daya reaktor secara akurat menggunakan kanal daya linier dan logaritmis; (3) Analisis Aktivasi Neutron — mengidentifikasi komposisi unsur material dengan mengaktifkannya menggunakan fluks neutron; (4) Produksi Radioisotop menghasilkan isotop radioaktif untuk keperluan medis dan industri; (5) Uji Material menguji ketahanan material terhadap paparan radiasi neutron; (6) Pendidikan & Pelatihan melatih operator dan supervisor reaktor nuklir bersertifikat sesuai standar BAPETEN.',
        materi10Title: 'Keamanan dan Regulasi',
        materi10Content: 'Reaktor Kartini beroperasi di bawah pengawasan ketat Badan Pengawas Tenaga Nuklir (BAPETEN) sesuai regulasi keselamatan nuklir internasional IAEA. Sistem keselamatan reaktor dirancang dengan filosofi pertahanan berlapis (defense in depth): setiap lapisan keselamatan berfungsi independen sehingga kegagalan satu lapisan tidak langsung menyebabkan kecelakaan. Sistem Instrumentasi & Kendali (SIK) Reaktor Kartini memantau parameter kritis — fluks neutron, periode reaktor, dan kondisi sistem pendingin secara real-time dan memicu SCRAM otomatis bila batas aman terlampaui. Setiap prosedur operasi mulai dari start-up, operasi pada tingkat daya, hingga shutdown normal maupun darurat wajib diikuti operator bersertifikat. Reaktor Kartini telah memiliki rekam jejak keselamatan yang sangat baik selama lebih dari 40 tahun beroperasi.',
        // ── Specs ──
        specTipe: 'TIPE',
        specDaya: 'DAYA NOMINAL',
        specBakar: 'BAHAN BAKAR',
        specModerator: 'MODERATOR',
        specModeratorVal: 'Air Ringan',
        specLokasi: 'LOKASI',
        specStatus: 'STATUS',
        specStatusVal: 'AKTIF',
        // ── Simulation Header ──
        nicknameTitle: 'IDENTIFIKASI OPERATOR',
        nicknameSubtitle: 'Masukkan nickname (maks. 5 huruf)',
        nicknameEmpty: 'Nickname tidak boleh kosong!',
        nicknameHint: 'NICKNAME AKAN DITAMPILKAN DI PANEL KONTROL',
        backBtn: '← KEMBALI',
        simTitle: 'GLOWLAB REAKTOR KARTINI',
        simSubtitle: 'GAME SIMULASI REAKTOR',
        labelDaya: 'DAYA',
        labelWaktu: 'WAKTU OPERASI',
        hintOrbit: 'Seret Putar · Gulir Perbesar',
        scramActive: 'SCRAM AKTIF',
        cherenkov: 'EFEK CHERENKOV',
        loading: 'Memuat...',
        resetScram: 'RESET SCRAM',
        resetSub: 'Klik untuk reset',
        scramCancel: 'Lepas untuk batalkan',
        scramHold: 'TAHAN UNTUK AKTIF',
        rodSafety: 'SAFETY',
        rodShim: 'SHIM',
        rodReg: 'REG',
        status: {
            OPERATING: 'OPERASI',
            SUBCRITICAL: 'SUBKRITIS',
            SHUTDOWN: 'SHUTDOWN',
            SCRAM: 'SCRAM',
        },
        simFase: 'FASE',
        simTarget: 'TARGET',
        simNow: 'SEKARANG',
        simWaktu: 'SISA WAKTU',
        simPoin: 'TOTAL POIN',
        // ── Control Panel ──
        title: 'PANEL KONTROL',
        apiOnline: 'API ONLINE',
        apiOffline: 'API OFFLINE',
        apiError: 'API ERROR',
        control: 'KONTROL',
        monitor: 'MONITOR',
        guide: 'PANDUAN',
        interlock: 'INTERLOCK',
        interlockOn: 'AKTIF',
        interlockOff: 'TIDAK AKTIF',
        interlockSubOn: 'Sistem interlock aktif – batang kendali siap dioperasikan',
        interlockSubOff: 'Tahan SHIFT untuk mengoperasikan batang kendali',
        shiftRequired: '⚠ Tekan Shift untuk mengoperasikan batang kendali',
        scramRequired: '⚠ Reaktor dalam kondisi SCRAM. Reset terlebih dahulu.',
        naikSign: '▲ NAIK',
        turunSign: '▼ TURUN',
        contPesan: 'Apakah Anda yakin ingin mengakhiri sesi simulasi ini? Anda akan melihat hasil akhir simulasi',
        contAktif: 'Aktifkan reaktor untuk memulai simulasi',
        contStabil: 'Stabilkan daya 90–110 kW selama 15 detik',
        contTurun: 'Turunkan semua batang kendali ke 0% sebelum mematikan reaktor!',
        contOn: 'Semua kontrol reaktor aktif',
        contTekan: 'Tekan untuk mengaktifkan reaktor',
        // ── Monitor Tab ──
        monitorTitle: 'DAYA REAKTOR',
        reactorOff: 'REAKTOR MATI',
        reactorOn: 'REAKTOR BEROPERASI',
        reactorSub: 'SUBKRITIS',
        reactorScram: 'SCRAM AKTIF',
        posisBatangKendali: 'POSISI BATANG KENDALI',
        // ── Guide Tab ──
        guideTitle: 'PANDUAN KEYBOARD',
        noteTitle: '⚠ CATATAN OPERASI',
        notes: [
            'Naikkan Safety Rod terlebih dahulu',
            'Gunakan Shim untuk reaktivitas kasar',
            'Regulating untuk fine-tuning daya',
            'SCRAM menurunkan semua batang ke 0%',
        ],
        guideRows: [
            { key: 'SHIFT', desc: 'Interlock – wajib ditekan' },
            { key: 'Shift + Q', desc: 'Safety Rod ▲ Naik' },
            { key: 'Shift + A', desc: 'Safety Rod ▼ Turun' },
            { key: 'Shift + W', desc: 'Shim Rod ▲ Naik' },
            { key: 'Shift + S', desc: 'Shim Rod ▼ Turun' },
            { key: 'Shift + E', desc: 'Regulating ▲ Naik' },
            { key: 'Shift + D', desc: 'Regulating ▼ Turun' },
        ],
        //── SkorPage ──
        skorTitle: 'SESI SIMULASI SELESAI',
        skorSubtitle: 'Glowlab Reaktor Kartini · Simulasi Tingkat Lanjut',
        skorLabel: 'SKOR',
        skorFeedback: 'Terima kasih telah menyelesaikan simulasi!',
        skorNote: 'Fitur penilaian segera hadir',
        skorSummary: 'Ringkasan Sesi',
        skorTstatus: 'STATUS AKHIR',
        skorStatus: 'Selesai',
        skorDaya: 'DAYA MAKS',
        skorHome: 'BERANDA',
        skorPanduan: 'PANDUAN',
        skorRestart: 'COBA LAGI',
        skorGrade: 'GRADE',
        skorWaktu: 'WAKTU',
        skorOperator: 'OPERATOR',
        skorPerfect: 'SEMPURNA!',
        skorGreat: 'SANGAT BAIK',
        skorGood: 'BAIK',
        skorOk: 'CUKUP',
        skorPractice: 'PERLU LATIHAN',
        skorThanks: 'Terima kasih telah menyelesaikan simulasi!',
        skorSummaryTitle: 'RINGKASAN SESI',
        skorLeaderboard: 'LEADERBOARD',
        skorNoData: 'Belum ada data',
        skorYou: 'KAMU',
        skorLabelStatus: 'STATUS',
        skorLabelSkor: 'SKOR',
        skorLabelPenalty: 'PENALTI',
        skorLabelBonus: 'BONUS',
        skorLabelTime: 'WAKTU',
        skorLabelOperator: 'OPERATOR',
        skorWin: 'MENANG!',
        skorTimeout: 'WAKTU HABIS',
        skorDone: 'SELESAI',
        skorMaxPoints: 'dari 3000 poin maksimal',
        // ── PowerDisplay ──
        tempCoolingDown: 'MENDINGIN',
        tempDanger: '🔴 SUHU BAHAYA',
        tempHigh: '△ SUHU TINGGI',
        tempNormal: 'SUHU NORMAL',
        tempIdle: 'SUHU IDLE',
        tempTitle: '🌡 SUHU PERMUKAAN REAKTOR',
        tempLegendWarning: 'PERINGATAN',
        tempLegendDanger: 'BAHAYA',
        powerDangerPower: '⚠ DAYA BAHAYA',
        powerNominal: 'DAYA NOMINAL',
        powerMedium: 'DAYA SEDANG',
        powerLow: 'DAYA RENDAH',
        powerTitle: '⚡ DAYA REAKTOR',
        // ── Rules Modal ──
        rulesSimGoalTitle: 'TUJUAN SIMULASI',
        rulesFaseLabel: 'FASE',
        rulesHowTitle: 'CARA MENGONTROL',
        rulesHowBody: 'Tekan dan tahan SHIFT sebagai interlock, lalu kombinasikan dengan tombol berikut untuk menggerakkan batang kendali:',
        rulesRodUpDown: '▲ Naik / ▼ Turun',
        rulesSeqTitle: 'URUTAN OPERASI YANG BENAR',
        rulesSeqBody: 'Reaktor hanya bisa beroperasi jika batang dinaikkan dengan urutan yang tepat:',
        rulesCoarseReactivity: 'reaktivitas kasar',
        rulesFineTuning: 'fine-tuning daya',
        rulesScramTitle: 'PERINGATAN SCRAM',
        rulesScramBody: 'Jaga daya tetap di bawah 110 kW. Jika daya menyentuh atau melebihi batas ini, sistem SCRAM otomatis aktif: semua batang kendali langsung jatuh ke 0% dan skor fase saat ini akan direset. Kamu juga bisa men-SCRAM manual lewat tombol SCRAM atau tombol R / T / Y di keyboard.',
        rulesWelcomeLabel: 'SELAMAT DATANG, ',
        rulesReadBefore: 'BACA ATURAN SEBELUM MEMULAI OPERASI REAKTOR',
        rulesGotIt: 'MENGERTI, MULAI!',
        rulesCameraTitle: 'KONTROL KAMERA 3D',
        rulesCameraBody: 'Gunakan kontrol berikut untuk menjelajahi tampilan 3D reaktor:',
        rulesComponentTitle: 'INFO KOMPONEN REAKTOR',
        rulesComponentBody: 'Tampilan 3D memiliki ikon huruf (A–H) yang menandai setiap komponen reaktor. Klik ikon huruf untuk melihat nama dan detail komponen. Klik ikon yang sama lagi untuk menutup keterangannya.',
        rulesComponentList: [
            { icon: 'A', name: 'Batang Keselamatan' },
            { icon: 'B', name: 'Batang Kompensasi' },
            { icon: 'C', name: 'Batang Pengatur' },
            { icon: 'D', name: 'Teras Reaktor' },
            { icon: 'E', name: 'Air Kolam' },
            { icon: 'F', name: 'Kolam Reaktor' },
            { icon: 'G', name: 'PC Operator' },
            { icon: 'H', name: 'Panel Kontrol' },
        ],
        // ── Control Panel Modal ──
        modalEndTitle: 'AKHIRI SESI SIMULASI?',
        btnCancel: 'BATAL',
        btnYesComplete: 'YA, SELESAIKAN',
        btnFinish: 'SELESAI',
        btnFinishLocked: '🔒 SELESAI',
        btnRestart: 'MULAI LAGI',
        powerWarnTitle: 'PERINGATAN!',
        btnUnderstood: 'MENGERTI',
        rodOrderWarnTitle: 'URUTAN BATANG KENDALI SALAH!',
        rodOrderWarnMsg: 'Naikkan Safety Rod terlebih dahulu sebelum mengoperasikan Shim atau Regulating Rod. Urutan yang benar: Safety → Shim → Regulating.',
        rodOrderWarnBtn: 'MENGERTI',
        reactorActiveLabel: 'REAKTOR AKTIF',
        // ── Win Overlay ──
        winTitle: 'SEMUA FASE SELESAI!',
        winTimeoutTitle: 'WAKTU HABIS!',
        winSubtitle: 'Kamu berhasil menyelesaikan seluruh 5 fase simulasi reaktor!',
        winTimeoutSubtitle: 'Batas waktu simulasi telah tercapai',
        winScoreLabel: 'SKOR AKHIR',
        winHint: 'Gunakan tombol SELESAI di Panel Kontrol untuk melihat hasil lengkap',
        // ── ReactorScene ──
        btnCloseDetail: '✕ TUTUP',
        btnMoreDetail: 'Lihat detail',
        // ── ErrorBoundary ──
        errTitle: 'Visualisasi 3D tidak tersedia',
        errSubtitle: 'Browser kamu mungkin tidak mendukung WebGL',
        // ── IRL Monitor ──
        irlTitle: 'IRL MONITOR',
        irlSubtitle: 'REAKTOR KARTINI · REAL-TIME',
        irlDataTime: 'DATA TIME',
        irlStatusLive: 'LIVE',
        irlStatusConn: 'MENGHUBUNGKAN...',
        irlStatusReconn: 'MENGHUBUNGKAN ULANG...',
        irlStatusError: 'ERROR',
        irlPanelThermal: '⬡ TERMAL',
        irlPanelHE: '⬡ PENUKAR PANAS',
        irlPanelWaterRes: '⬡ RESISTANSI AIR',
        irlPanelRadiation: '⬡ PAPARAN RADIASI',
        irlRodSafety: 'SAFETY',
        irlRodComp: 'SHIM',
        irlRodReg: 'REGULATING',
        irlReconnMsg: 'MENGHUBUNGKAN ULANG KE STREAM...',
        irlConnMsg: 'MENGHUBUNGKAN...',
        irlInitMsg: 'Memuat...',
    },

    en: {
        // ── Home & Prepare ──
        homeDescription: 'Virtual simulation of Kartini Reactor – TRIGA Mark II Research Reactor owned by BRIN Yogyakarta. Control rods, monitor reactor power, and learn nuclear reactor physics safely.',
        homeSubtitle: 'INTERACTIVE SIMULATOR SYSTEM',
        homeProfesi: 'GLOWLAB KARTINI',
        profesiTitle: 'Choose Your Role',
        profesiDesc: 'Sign in as?',
        profesiAhli: 'Master',
        profesiPemula: 'Beginner',
        homePilih: 'CHOOSE SIMULATION MODE',
        homeKet: 'Standard mode for demonstration & learning, or advanced mode with real reactor data.',
        homeBack: '←',
        homePilihGame: 'SIMULATION GAME',
        homePilihKet: 'With scoring & gamification',
        homePilihGame1: 'IRL MODE',
        homePilihKet1: 'Real-time reactor data, no scoring',
        feature1Title: 'LEARNING ZONE',
        feature1Desc: 'Understand the reactor structure, main components, and operating principles of the TRIGA Mark II research reactor',
        feature2Title: 'EARLY CHALLENGE',
        feature2Desc: 'Start your journey with an initial exam to test your basic understanding of nuclear reactors',
        feature3Title: 'SIMULATED ARENA',
        feature3Desc: 'Test your ability to manage reactor power to ensure stable operation',
        feature4Title: 'FINAL CHALLENGE',
        feature4Desc: 'Take a final exam to test your understanding of nuclear reactors',
        // ── Materi Page ──
        materiPageTitle: 'KARTINI REACTOR MATERIAL',
        materiPageSubtitle: 'BASIC KNOWLEDGE OF NUCLEAR REACTOR',
        materiBack: '← BACK',
        materiProgress: 'READING COMPLETE',
        materiReadAll: 'Mark as Done',
        materiDone: '✓ Material Completed',
        materiProgressLabel: 'READING PROGRESS',
        materiDoneBanner: 'Congratulations! You have completed all materials. Learning Zone is complete!',
        materiTagDone: 'DONE',
        materiBackGuide: '← BACK TO GUIDE',
        materi1Title: 'What is the Kartini Reactor?',
        materi1Content: 'The Kartini Reactor is a TRIGA Mark II research nuclear reactor facility owned and operated by the National Research and Innovation Agency (BRIN) in Yogyakarta, Indonesia. As a nuclear reactor, it serves as an installation where continuous and controlled nuclear fission reactions take place. The reactor has a nominal power of 100 kW and has been in operation since 1979. The name "Kartini" is taken from national hero R.A. Kartini as a symbol of scientific progress and emancipation. The Kartini Reactor is used for nuclear reactor physics research, radioisotope production, education, and training of national nuclear experts.',
        materi2Title: 'Brief History',
        materi2Content: 'The Kartini Reactor was built in 1974 and officially began operating in 1979. It was designed and manufactured by General Atomics, USA. The facility is managed by the Center for Science and Technology of Accelerators (PSTA) BATAN Yogyakarta — now part of BRIN. For over four decades, the Kartini Reactor has been the backbone for nuclear reactor physics research, certified reactor operator education, and nuclear competency development in Indonesia. It remains one of the oldest nuclear facilities still actively operating in Indonesia.',
        materi3Title: 'TRIGA Mark II Type',
        materi3Content: 'TRIGA (Training, Research, Isotopes, General Atomics) Mark II is a type of research reactor specifically designed for training, research, and isotope production. Its main advantage is a very high safety factor due to the use of U-ZrH (Uranium-Zirconium Hydride) fuel which has a negative temperature coefficient. This means when fuel temperature rises due to a power increase, reactor reactivity automatically decreases, causing the power to drop on its own (self-limiting). This negative temperature feedback mechanism makes TRIGA reactors inherently safe and resistant to runaway conditions. The Kartini Reactor as a TRIGA Mark II uses light water (H₂O) as both moderator and coolant.',
        materi4Title: 'Main Reactor Components',
        materi4Content: 'The Kartini Reactor consists of several main components working in an integrated manner: (1) Reactor Core — where nuclear fission reactions occur, containing U-ZrH fuel elements; (2) Control Rods — consisting of Safety Rod, Shim Rod, and Regulating Rod to control reactivity; (3) Moderator & Coolant — uses light water (H₂O) to slow down neutrons while simultaneously cooling the reactor; (4) Instrumentation & Control System (ICS) — monitors neutron flux using CIC (Compensated Ionization Chamber) type detectors and displays operating parameters in real-time; (5) Reactor Protection System — a layered safety system ensuring safe operation and triggering automatic SCRAM; (6) Biological Shield — protects operators and the environment from radiation exposure.',
        materi5Title: 'Control Rods',
        materi5Content: 'Control rods are critical components in reactor operation that regulate the fission rate by absorbing neutrons. The Kartini Reactor has three types of control rods: (1) Safety Rod — made from very strong neutron-absorbing material such as Cadmium, used during start-up and emergency shutdown (SCRAM); must be at 100% position for the reactor to operate; (2) Shim Rod (Compensation Rod) — used for coarse reactivity control, raising and lowering reactor power in large increments; (3) Regulating Rod — used for precise fine-tuning of reactor power at stable operating level. The reactor control system operates in three loops: start-up loop (raising power), operating loop (maintaining stable power), and shutdown loop (shutting down the reactor).',
        materi6Title: 'Nuclear Reactor Working Principle',
        materi6Content: 'A nuclear reactor works on the principle of a controlled chain fission reaction. Thermal neutrons (energy ~0.025 eV, speed 2200 m/s) strike Uranium-235 nuclei, forming an unstable compound nucleus U-236 that immediately splits into two fission products, releasing 2–3 new neutrons and approximately 200 MeV of energy per fission. These new neutrons are slowed by the moderator (light water) from fast energy to thermal energy, then strike other U-235 nuclei creating a chain reaction. Reactor power changes are governed by reactivity (ρ): positive reactivity (k>1) raises power, zero reactivity (k=1) maintains stable power at the critical state, and negative reactivity (k<1) lowers power to a subcritical state.',
        materi7Title: 'SCRAM Safety System',
        materi7Content: 'SCRAM is the reactor emergency shutdown system that operates automatically when abnormal conditions are detected. The Kartini Reactor protection system is designed with a defense-in-depth philosophy: (1) Basic Defense Layer — ensures the reactor operates within normal bounds; (2) Disturbance Prevention Layer — detects abnormal conditions before they become dangerous; (3) Automatic Trip System — drops all control rods to 0% within seconds when reactor parameters exceed safe limits. SCRAM actuation parameters include excess power, excessively rapid power rise rate (short reactor period), and coolant system failure. After SCRAM, the reactor can only be restarted after a manual reset by a certified operator to confirm the cause of SCRAM has been resolved.',
        materi8Title: 'Cherenkov Effect',
        materi8Content: 'The Cherenkov effect is the blue light visible in nuclear reactor pools. This phenomenon occurs when charged particles (such as electrons from radiation) move through water at speeds higher than the speed of light in that medium. Similar to a sonic boom from a supersonic aircraft, these very fast-moving particles produce a "light explosion" that appears blue-purple. This effect is a sign that the reactor is actively operating.',
        materi9Title: 'Uses of Kartini Reactor',
        materi9Content: 'The Kartini Reactor has various important functions for science and technology: (1) Reactor Physics Research — studying reactor kinetics, control rod reactivity measurement, fuel temperature coefficients, reactor criticality, and neutron flux distribution; (2) Power Calibration — performing accurate measurements and calibration of linear and logarithmic reactor power channels; (3) Neutron Activation Analysis — identifying elemental composition of materials by activating them with neutron flux; (4) Radioisotope Production — generating radioactive isotopes for medical and industrial applications; (5) Material Testing — testing material resistance to neutron radiation exposure; (6) Education & Training — training certified reactor operators and supervisors according to BAPETEN standards.',
        materi10Title: 'Safety and Regulation',
        materi10Content: 'The Kartini Reactor operates under strict supervision of the Nuclear Energy Regulatory Agency (BAPETEN) in accordance with IAEA international nuclear safety regulations. The reactor safety system is designed with a defense-in-depth philosophy: each safety layer functions independently so that failure of one layer does not directly cause an accident. The Instrumentation & Control System (ICS) monitors critical parameters — neutron flux, reactor period, and coolant system conditions — in real-time and triggers automatic SCRAM if safe limits are exceeded. Every operational procedure — from start-up, power level operation, to normal and emergency shutdown — must be followed by certified operators. The Kartini Reactor has had an excellent safety record for over 40 years of operation.',
        // ── Navigasi & Button ──
        btnSelengkapnya: 'LEARN MORE →',
        btnMulai: 'START SIMULATION →',
        btnKembali: '← BACK',
        hintKlik: 'Click to start the interactive simulation',
        // ── Footer ──
        footerText: '© 2026 Kartini Reactor Simulator | BRIN Indonesia',
        footerSub: 'Designed for educational and simulation purposes',
        // ── Section Labels ──
        sectionFeature: 'USAGE GUIDE',
        labelSpesifikasi: 'SPECIFICATIONS',
        specsTitle: '⚛ REACTOR SPECIFICATIONS',
        requirementHint: 'Complete Step 1 & 2 to unlock the simulation',
        //--feature card
        progressLabel: 'LEARNING PROGRESS',
        progressLocked: 'Complete this first:',
        progressDone: 'Step completed!',
        progressIncomplete: 'Complete all steps first!',
        progressReset: ' Progress reset',
        resetProgress: '↺ Reset Progress',
        stepDone: ' Done',
        stepOpen: ' Open',
        stepLocked: ' Locked',
        // ── Specs ──
        specTipe: 'TYPE',
        specDaya: 'NOMINAL POWER',
        specBakar: 'FUEL',
        specModerator: 'MODERATOR',
        specModeratorVal: 'Light Water',
        specLokasi: 'LOCATION',
        specStatus: 'STATUS',
        specStatusVal: 'ACTIVE',
        // ── Simulation Header ──
        nicknameTitle: 'OPERATOR IDENTIFICATION',
        nicknameSubtitle: 'Enter your nickname (max. 5 characters)',
        nicknameEmpty: 'Nickname cannot be empty!',
        nicknameHint: 'NICKNAME WILL BE SHOWN ON CONTROL PANEL',
        backBtn: '← BACK',
        simTitle: 'GLOWLAB KARTINI REACTOR',
        simSubtitle: 'REACTOR SIMULATION GAME',
        labelDaya: 'POWER',
        labelWaktu: 'OPERATION TIME',
        hintOrbit: 'Drag Rotate · Scroll Zoom',
        scramActive: 'SCRAM ACTIVE',
        cherenkov: 'CHERENKOV EFFECT',
        loading: 'Loading...',
        resetScram: 'RESET SCRAM',
        resetSub: 'Click to reset',
        scramCancel: 'Release to cancel',
        scramHold: 'HOLD TO ACTIVATE',
        rodSafety: 'SAFETY',
        rodShim: 'SHIM',
        rodReg: 'REG',
        status: {
            OPERATING: 'OPERATING',
            SUBCRITICAL: 'SUBCRITICAL',
            SHUTDOWN: 'SHUTDOWN',
            SCRAM: 'SCRAM',
        },
        simFase: 'PHASE',
        simTarget: 'TARGET',
        simNow: 'CURRENT',
        simWaktu: 'TIME LEFT',
        simPoin: 'TOTAL POINTS',
        // ── Control Panel ──
        title: 'CONTROL PANEL',
        apiOnline: 'API ONLINE',
        apiOffline: 'API OFFLINE',
        apiError: 'API ERROR',
        control: 'Control',
        monitor: 'Monitor',
        guide: 'Guide',
        interlock: 'INTERLOCK',
        interlockOn: 'ACTIVE',
        interlockOff: 'INACTIVE',
        interlockSubOn: 'Interlock active – control rods ready to operate',
        interlockSubOff: 'Hold SHIFT to operate control rods',
        shiftRequired: '⚠ Press Shift to operate control rods',
        scramRequired: '⚠ Reactor is in SCRAM condition. Reset first.',
        naikSign: '▲ UP',
        turunSign: '▼ DOWN',
        contPesan: 'Are you sure you want to end this simulation session? You will see the final simulation results.',
        contAktif: 'Activate the reactor to start the simulation',
        contStabil: 'Stabilize the power at 90–110 kW for 15 seconds',
        contTurun: 'Lower all control rods to 0% before shutting down the reactor!',
        contOn: 'All reactor controls are active',
        contTekan: 'Press to activate the reactor',
        // ── Monitor Tab ──
        monitorTitle: 'REACTOR POWER',
        reactorOff: 'REACTOR OFF',
        reactorOn: 'REACTOR OPERATING',
        reactorSub: 'SUBCRITICAL',
        reactorScram: 'SCRAM ACTIVE',
        posisBatangKendali: 'CONTROL ROD POSITION',
        // ── Guide Tab ──
        guideTitle: 'KEYBOARD GUIDE',
        noteTitle: '⚠ OPERATION NOTES',
        notes: [
            'Raise Safety Rod first',
            'Use Shim for coarse reactivity',
            'Regulating for fine power tuning',
            'SCRAM drops all rods to 0%',
        ],
        guideRows: [
            { key: 'SHIFT', desc: 'Interlock – must be held' },
            { key: 'Shift + Q', desc: 'Safety Rod ▲ Up' },
            { key: 'Shift + A', desc: 'Safety Rod ▼ Down' },
            { key: 'Shift + W', desc: 'Shim Rod ▲ Up' },
            { key: 'Shift + S', desc: 'Shim Rod ▼ Down' },
            { key: 'Shift + E', desc: 'Regulating ▲ Up' },
            { key: 'Shift + D', desc: 'Regulating ▼ Down' },
        ],
        //── SkorPage ──
        skorTitle: 'SIMULATION SESSION ENDED',
        skorSubtitle: 'Glowlab Kartini Reactor · Advanced Simulation',
        skorLabel: 'SCORE',
        skorFeedback: 'Thank you for completing the simulation!',
        skorNote: 'Scoring feature coming soon',
        skorSummary: 'Session Summary',
        skorTstatus: 'FINAL STATUS',
        skorStatus: 'Completed',
        skorDaya: 'MAX POWER',
        skorHome: 'HOME',
        skorPanduan: 'GUIDE',
        skorRestart: 'TRY AGAIN',
        skorGrade: 'GRADE',
        skorWaktu: 'TIME',
        skorOperator: 'OPERATOR',
        skorPerfect: 'PERFECT!',
        skorGreat: 'EXCELLENT',
        skorGood: 'GOOD',
        skorOk: 'FAIR',
        skorPractice: 'KEEP PRACTICING',
        skorThanks: 'Thank you for completing the simulation!',
        skorStabilized: '🏆 Reactor successfully stabilized!',
        skorComingSoon: 'Scoring feature coming soon',
        skorSummaryTitle: 'SESSION SUMMARY',
        skorLeaderboard: 'LEADERBOARD',
        skorNoData: 'No data yet',
        skorYou: 'YOU',
        skorLabelStatus: 'STATUS',
        skorLabelSkor: 'SCORE',
        skorLabelPenalty: 'PENALTY',
        skorLabelBonus: 'BONUS',
        skorLabelTime: 'TIME',
        skorLabelOperator: 'OPERATOR',
        skorWin: 'WIN!',
        skorTimeout: "TIME'S UP",
        skorDone: 'DONE',
        skorMaxPoints: 'out of 3000 max points',
        // ── PowerDisplay ──
        tempCoolingDown: 'COOLING DOWN',
        tempDanger: '🔴 DANGER TEMP',
        tempHigh: '△ HIGH TEMP',
        tempNormal: 'NORMAL TEMP',
        tempIdle: 'IDLE TEMP',
        tempTitle: '🌡 REACTOR SURFACE TEMP',
        tempLegendWarning: 'WARNING',
        tempLegendDanger: 'DANGER',
        powerDangerPower: '⚠ DANGER POWER',
        powerNominal: 'NOMINAL POWER',
        powerMedium: 'MEDIUM POWER',
        powerLow: 'LOW POWER',
        powerTitle: '⚡ REACTOR POWER',
        // ── Rules Modal ──
        rulesSimGoalTitle: 'SIMULATION GOAL',
        rulesFaseLabel: 'PHASE',
        rulesHowTitle: 'HOW TO CONTROL',
        rulesHowBody: 'Hold SHIFT as the interlock, then combine it with the following keys to move the control rods:',
        rulesRodUpDown: '▲ Up / ▼ Down',
        rulesSeqTitle: 'CORRECT OPERATING SEQUENCE',
        rulesSeqBody: 'The reactor can only operate if rods are raised in the correct order:',
        rulesCoarseReactivity: 'coarse reactivity',
        rulesFineTuning: 'fine power tuning',
        rulesScramTitle: 'SCRAM WARNING',
        rulesScramBody: 'Keep power below 110 kW. If power reaches or exceeds this limit, the automatic SCRAM system activates: all control rods immediately drop to 0% and the current phase score will be reset. You can also manually SCRAM using the SCRAM button or the R / T / Y keys.',
        rulesWelcomeLabel: 'WELCOME, ',
        rulesReadBefore: 'READ THE RULES BEFORE OPERATING THE REACTOR',
        rulesGotIt: 'GOT IT, START!',
        rulesCameraTitle: '3D CAMERA CONTROLS',
        rulesCameraBody: 'Use the following controls to explore the 3D reactor view:',
        rulesComponentTitle: 'REACTOR COMPONENT INFO',
        rulesComponentBody: 'The 3D view has letter icons (A–H) marking each reactor component. Click a letter icon to see its name and details. Click the same icon again to close the info card.',
        rulesComponentList: [
            { icon: 'A', name: 'Safety Rod' },
            { icon: 'B', name: 'Shim Rod' },
            { icon: 'C', name: 'Regulating Rod' },
            { icon: 'D', name: 'Reactor Core' },
            { icon: 'E', name: 'Pool Water' },
            { icon: 'F', name: 'Reactor Pool' },
            { icon: 'G', name: 'Operator PC' },
            { icon: 'H', name: 'Control Panel' },
        ],
        // ── Control Panel Modal ──
        modalEndTitle: 'END SIMULATION SESSION?',
        btnCancel: 'CANCEL',
        btnYesComplete: 'YES, COMPLETE',
        btnFinish: 'FINISH',
        btnFinishLocked: '🔒 FINISH',
        btnRestart: 'RESTART',
        powerWarnTitle: 'WARNING!',
        btnUnderstood: 'Get It',
        rodOrderWarnTitle: 'WRONG ROD ORDER!',
        rodOrderWarnMsg: 'Raise the Safety Rod first before operating the Shim or Regulating Rod. Correct order: Safety → Shim → Regulating.',
        rodOrderWarnBtn: 'UNDERSTOOD',
        reactorActiveLabel: 'REACTOR ACTIVE',
        // ── Win Overlay ──
        winTitle: 'ALL PHASES COMPLETE!',
        winTimeoutTitle: "TIME'S UP!",
        winSubtitle: 'You successfully completed all 5 reactor simulation phases!',
        winTimeoutSubtitle: 'Simulation time limit has been reached',
        winScoreLabel: 'FINAL SCORE',
        winHint: 'Use the FINISH button on the Control Panel to see full results',
        // ── ReactorScene ──
        btnCloseDetail: '✕ CLOSE',
        btnMoreDetail: 'More detail',
        // ── ErrorBoundary ──
        errTitle: '3D visualization is not available',
        errSubtitle: 'Your browser might not support WebGL',
        // ── IRL Monitor ──
        irlTitle: 'IRL MONITOR',
        irlSubtitle: 'KARTINI REACTOR · REAL-TIME',
        irlDataTime: 'DATA TIME',
        irlStatusLive: 'LIVE',
        irlStatusConn: 'CONNECTING...',
        irlStatusReconn: 'RECONNECTING...',
        irlStatusError: 'ERROR',
        irlPanelThermal: '⬡ THERMAL',
        irlPanelHE: '⬡ HEAT EXCHANGER',
        irlPanelWaterRes: '⬡ WATER RESISTANCE',
        irlPanelRadiation: '⬡ RADIATION EXPOSURE',
        irlRodSafety: 'SAFETY',
        irlRodComp: 'SHIM',
        irlRodReg: 'REGULATING',
        irlReconnMsg: 'RECONNECTING TO STREAM...',
        irlConnMsg: 'CONNECTING...',
        irlInitMsg: 'Loading...',
    },
}

// ── Context ──
const LanguageContext = createContext(null)

// ── Provider ──
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        try {
            const saved = localStorage.getItem('reaktor-language')
            if (saved === 'id' || saved === 'en') return saved
        } catch (e) {
            console.warn('localStorage tidak tersedia:', e)
        }
        return 'id'
    })

    useEffect(() => {
        try {
            localStorage.setItem('reaktor-language', language)
        } catch (e) {
            console.warn('Gagal menyimpan bahasa:', e)
        }
    }, [language])

    const changeLanguage = (lang) => {
        if (lang === 'id' || lang === 'en') {
            setLanguage(lang)
        }
    }

    const t = (key) => {
        return translations[language]?.[key] || translations['id']?.[key] || key
    }

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage: changeLanguage,
            t,
            ...translations[language],
        }}>
            {children}
        </LanguageContext.Provider>
    )
}

// ── Hook - HANYA SATU ──
export function useLanguage() {
    const context = useContext(LanguageContext)
    if (!context) {
        throw new Error('useLanguage harus digunakan dalam LanguageProvider')
    }
    return context
}

export default LanguageContext